### ISSUE TITLE
[1.19.2] Crash by ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ffuentesm** [Asek3/Rubidium#273] opened 2022-09-14 19:38 UTC
![image](https://user-images.githubusercontent.com/44974827/190246664-9dbe25d9-ef7f-42fc-9334-b128fcd6d5f2.png)

log: https://crashy.net/kh2yAx9xHOGOZeHLFxgf
https://crashy.net/nTMnoHSOcBhdbH2e7UPv
Crash report: https://crashy.net/kh2yAx9xHOGOZeHLFxgf?raw
https://crashy.net/nTMnoHSOcBhdbH2e7UPv?raw

**Comment by coderepo8593** [comment] 2022-09-15 16:45
So, if we look at the logs we'll see a list of mixins for calls in the callstack.

re:mixin
pl:accesstransformer:B
pl:runtimedistcleaner:A
re:classloading
pl:accesstransformer:B
pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient
pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient
pl:mixin:APP:neat.mixins.json:MinecraftMixin
pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft
pl:mixin:APP:balm.mixins.json:MinecraftMixin
pl:mixin:APP:mixin.cleancut.json:MinecraftMixin
pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin
pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin
pl:mixin:APP:architectury.mixins.json:MixinMinecraft
pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin
pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess
pl:mixin:APP:iceberg.mixins.json:MinecraftMixin
pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A

That should make them a lot more readable. From here, we see that we have some mixins that are easy to recognize which mod they come from just by the name. It is likely that the crash isn't being caused by one of the libraries, so we won't start there. Although we might end up having to look at libraries after ruling out the other mixins. 

So we have: Cleancut, Ars Nouveau, Immersive Engineering, Iceberg, Better Thirdperson, and Spyglass Improvements.

Of these, the two that interact with are most likely to have more substantive rendering code are going to be Better Thirdperson and Spyglass Improvements, which I hope is obvious based upon what they do. That doesn't mean they are causing the problem, it just means we should rule these out first before checking on other mods.

Here is what you should do:
1. Remove Better Thirdperson and Spyglass Improvements, see if it crashes. If it doesn't, then you know one of those mods or the combination of them is likely the cause.
2. If it still crashes, one of the other mods is causing the crash.
3. Remove Immersive Engineering, see if it crashes. If it doesn't, then we are quickly exhausting what is causing this crash. The other mods don't seem like they are likely to cause this issue, and the remaining mod that would, Ars Nouveau, is widely used and hasn't been known to cause crashes with Rubidium. Immersive Engineering is also widely used, but I have never tested it myself.  It's possible a recent update has created a bug where one did not exist before.

Continue to test using the process explained until you discover the mod by trial and error. Yes, this is currently the best troubleshooting process to locate the problem. Once you do, provide a full description as to the circumstances under which the crash occurs.

Does it happen as soon as you load? Does it happen in a specific chunk with specific structure or entities/blocks? Is there any TPS lag before the crash or does it occur abruptly? And so on and so on.

All these things arm the mod authors with information to more quickly address and realize what the root cause is. The less information you provide the longer it will take to handle or the more likely it will not be worth the time investment to resolve due to the other fixes and features the mod authors have to implement.

**Comment by coderepo8593** [comment] 2022-09-23 16:21
Immersive Engineering is incompatible with Rubidium, see https://github.com/Asek3/Rubidium/issues/270

**Comment by Asek3** [comment] 2023-09-20 07:43
Fixed on latest versions

**Closed as completed by Asek3** 2023-09-20 07:43 UTC
