### ISSUE TITLE
[1.18.2] Immersive Engineering Wires not rendering

### ISSUE THREAD

**Issue by spooknik** [Asek3/Rubidium#152] opened 2022-06-13 06:21 UTC
#### Forge 
40.1.31

#### Mods

- Rubidium 0.5.2
- Immersive Engineering 1.18.2-8.0.1-147

#### Steps to reproduce the issue
Try to place any wire between two relays with both mods loaded. 

#### Additional details
Removing Rubidium and restarting the game makes the wires visible again.

**Comment by brucethemoose** [comment] 2022-06-14 13:01
Duplicate of #89 

But yes... I get this too.

**Comment by D4RKAR117** [comment] 2022-06-15 14:23
I got that issue too, i managed to workaround with [this](https://github.com/BluSunrize/ImmersiveEngineering/issues/5300#issuecomment-1139724675). since the bug its caused by the sodium fork and will not be included at IE codebase it hink that this sould be part of rubidium code, but until that happens this should work.

**Comment by brucethemoose** [comment] 2022-06-15 15:30
Yep. For reference, the newest version of the fix is here: https://github.com/malte0811/rubie/releases/latest

**Comment by spooknik** [comment] 2022-06-15 20:05
> Yep. For reference, the newest version of the fix is here: https://github.com/malte0811/rubie/releases/latest

Works for me 👍

**Closed as completed** 2022-07-19 12:43 UTC
