### ISSUE TITLE
1.16.5 - Crash after loading into world

### ISSUE THREAD

**Issue by SteaSteaStea** [Asek3/Rubidium#131] opened 2022-05-19 03:45 UTC
I am using better end reforked which should be compatible.
The game crashed after loading into my world.
Using [Rubidium mc1.16.5-0.2.6]
https://crashy.net/0Oe1KWAR2HMUiQwHfzAX

**Comment by Delfite** [comment] 2022-05-31 04:41
I'm having a similar issue, however this one seems to be caused by Faulty Mixins: https://pastebin.com/6NYyad6P

**Comment by Asek3** [comment] 2022-08-12 16:02
Should be fixed in last releases

**Closed as completed by Asek3** 2022-08-12 16:02 UTC
