### ISSUE TITLE
Crash (Create: Above and Beyond modpack)

### ISSUE THREAD

**Issue by road2react** [Asek3/Rubidium#141] opened 2022-06-03 04:03 UTC
Hello,

I am starting the Create: Above and Beyond modpack.

I added Rubidium and Oculus to the modpack and updated the forge version to latest. 

After creating a world, I noticed a strange issue. Most blocks render normally. However, all blocks above y=80 are invisible.

![Screenshot](https://cdn.discordapp.com/attachments/882744552610480149/982101817053814825/unknown.png)

Placing blocks on the ground works normally. However, placing a block above y=80 immediately crashes the game.

The crash and errors occur with Oculus removed.

Here is the stack trace: https://hst.sh/otimusexiv.sql

**Comment by enkido** [comment] 2022-06-08 18:18
![image](https://user-images.githubusercontent.com/6398971/172689058-cb7544b0-a217-44f3-8e76-4e61f534212e.png)

Same problem, just rubidium + A&B, everything above 79 is gone, placing a block crashes the game
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException

https://hst.sh/xivupadege.rb

**Comment by enkido** [comment] 2022-06-09 20:57
I have isolated the problem. It is caused by "cavebiomeapi-1.16.5-1.3.7.jar". 
I have tested it just with: 
- rubidium-0.2.6.jar
- cavebiomeapi-1.16.5-1.3.7.jar

With the "cavebiomeapi-1.16.5-1.3.7.jar" the problem appears and without everything is fine.

**Comment by enkido** [comment] 2022-06-09 21:39
Furthermore, with Version "cavebiomeapi-1.16.5-1.4.2.jar" the problem no longer appears and seems to be resolved. But this will change terrain generation for existing worlds.

**Comment by Asek3** [comment] 2022-06-20 10:07
Fixed in 0.2.7

**Closed as completed by Asek3** 2022-06-20 10:07 UTC
