### ISSUE TITLE
Conflict with Effective

### ISSUE THREAD

**Issue by Reshy** [Asek3/Rubidium#223] opened 2022-08-08 14:11 UTC
The graphical mod Effective seems to have a conflict with Rubidium that prevents the mist clouds from appearing.  

Without Rubidium:
![2022-08-08_07 08 09](https://user-images.githubusercontent.com/2096384/183437991-db1f0d7a-7303-49fd-ba72-677d12094d68.png)

With Rubidium:
![2022-08-08_07 10 31](https://user-images.githubusercontent.com/2096384/183438000-b48f9e65-4b10-4cd5-b0b9-ae273608b5fe.png)

**Comment by Asek3** [comment] 2023-09-08 18:32
Duplicate of #27

**Closed as completed by Asek3** 2023-09-08 18:32 UTC
