### ISSUE TITLE
Effective 1.18.2 cascade particles not showing.

### ISSUE THREAD

**Issue by Swagboi7** [Asek3/Rubidium#156] opened 2022-06-14 17:28 UTC
Every other feature works with Rubidium except the fancy cascades. Quite annoying since it’s one of my favorite features.

**Comment by DadoIrie** [comment] 2023-06-11 09:16
found a workaround (without excluding rubidium ofc) @Swagboi7 ?
can confirm this and would be awesome if could be looked into it

**Comment by Asek3** [comment] 2023-09-08 18:32
duplicate of #27

**Closed as completed by Asek3** 2023-09-08 18:32 UTC
