### ISSUE TITLE
[1.16.5] BetterEnd Reforged 2.5 + Forgery 1.4.0_01 Causes bug and crash when installed with rubidium

### ISSUE THREAD

**Issue by DoodlyDrawn** [Asek3/Rubidium#250] opened 2022-08-24 22:00 UTC
when running rubidium 2.0.10 with betterend reforged 2.5 alone, it works well.
when i run rubidium with all of my other mods without betterend it also works well.
however, once i load rubidium with betterend and all of the other mods it recreates the same issue with world rendering

images of the issue:
![2022-08-25_00 11 35](https://user-images.githubusercontent.com/100347283/186530333-79caa84f-8a53-4488-b4a9-f34df5bb9689.png)
![2022-08-25_00 11 34](https://user-images.githubusercontent.com/100347283/186530358-15ba2f98-90b5-4d5f-9288-da431dff1ff0.png)
![2022-08-25_00 11 26](https://user-images.githubusercontent.com/100347283/186530361-93a1e498-3c5e-4a27-be0e-43a4d5ee18db.png)
![2022-08-25_00 11 21](https://user-images.githubusercontent.com/100347283/186530398-b108ca11-c51b-4cfd-bc77-e7d292e5533c.png)

the crashlog:
[crash-2022-08-25_00.11.40-client.txt](https://github.com/Asek3/Rubidium/files/9419660/crash-2022-08-25_00.11.40-client.txt)
note that according to the crashlog there seems to be some issue relating to betterend mixins

also, is there a way that i can send you the mods that i used? the zip file i've compiled containing all of the mods is 405MB and github doesn't allow me to upload it, once you have it you should be able to recreate the problem.

final note, i was also using the newest occulus 1.2.6.

Edit:
i also noticed the other mixins in the crashlog, so perhaps the crashlog doesn't quite help...

**Comment by coderepo8593** [comment] 2022-08-30 17:57
How did you come to the conclusion that this was being caused by BetterEnd Reforked? This version of BetterEnd is known to actually be compatible. I am able to run it without issue.

Your actual problem is Forgery. It is what is causing the crash. See my issue here.
https://github.com/Asek3/Rubidium/issues/262

For the time being, until either the Forgery developer or Asek have time to take a look, you can run Forgery on the server side and remove it from the client.

**Comment by coderepo8593** [comment] 2022-08-30 17:58
Other important note. When you are looking at the log file, check all the render mixins that are in the call stack, as they could also be causing the problem. It's a good first place to look.

**Comment by coderepo8593** [comment] 2022-08-30 18:15
I have created this Issue on Forgery's tracker
https://github.com/unascribed/Fabrication/issues/539

**Comment by DoodlyDrawn** [comment] 2022-08-30 20:48
> I have created this Issue on Forgery's tracker [unascribed/Fabrication#539](https://github.com/unascribed/Fabrication/issues/539)

i have tried with and without forgery with all of the mods that i've used, and have confirmed your statement
it is indeed forgery which causes the issue, but **only** when it's installed alongside betterend, other then that forgery seems to work with rubidium, maybe they both alter something which is essential to betterend 2.5 solution to sodium compatibility...

**Comment by DoodlyDrawn** [comment] 2022-08-30 21:16
i've now also tested with just forgery and betterend, and have confirmed that when the two are together they are causing the issue with rubidium
[crash-2022-08-31_00.10.53-client.txt](https://github.com/Asek3/Rubidium/files/9456693/crash-2022-08-31_00.10.53-client.txt)

edit1:
![2022-08-31_00 19 10](https://user-images.githubusercontent.com/100347283/187546600-3917f3d5-3a4e-4214-bb72-fd3a280e0ab5.png)

edit2:
so to reiterate, so far we've found that betterend 2.5 **is compatible** with rubidium, similarly Forgery 1.4.0_01 **is also compatible** with rubidium, **however** when both are installed together with rubidium the issue emerges.
as @coderepo8593 explained Forgery does something with the mixins which causes the issue of betterend-rubidium to reappear

i'm also adding the log file for this, it's fairly short.
[latest.log](https://github.com/Asek3/Rubidium/files/9456844/latest.log)

**Comment by DoodlyDrawn** [comment] 2022-08-30 21:58
based on all of this this isn't a problem with rubidium then, but a problem with the way **BetterEnd 2.5** and **Forgery 1.4.0_01** modify/inject mixins which somehow relate to the compatibility added by @Someone-Else-Was-Taken between BetterEnd and Sodium for Forge.

Not sure whether to close the issue, if there is anything which @Asek3 can do about it, for now it'll remain open, if there is nothing that can be done from @Asek3's then the issue can be closed by @Asek3.

**Comment by SuperFeda** [comment] 2022-08-31 06:58
(I apologize if I misunderstood anything in your dialogue because my English is very, VERY bad).

I also have a modpack on Rubidium and when I add BetterEnd reforked to it and teleport to far end islands I crash the game.

Crash report: https://github.com/SuperPypok/CrashReport-rubidium-and-betterend-

(DeepL translate)

**Comment by coderepo8593** [comment] 2022-08-31 13:34
@SuperPypok You will want to create a separate issue for your problem, it is different than the one that is described here.

@DoodlyDrawn interesting, I am using BetterEnd as well, but I thought I had removed BetterEnd and still had the problem. I will have to test again.

**Comment by SuperFeda** [comment] 2022-08-31 13:35
> @SuperPypok You will want to create a separate issue for your problem, it is different than the one that is described here.

Ok

**Comment by coderepo8593** [comment] 2022-08-31 14:00
@SuperPypok Your name is interesting by the way. пупок if it is Russian and it is also commonly used by those who speak Yiddish, usually by grandparents who are showing their affection to a dear little child. Taken literally however, it is quite funny and a little absurd.

**Comment by SuperFeda** [comment] 2022-08-31 15:53
> @SuperPypok Your name is interesting by the way. пупок if it is Russian and it is also commonly used by those who speak Yiddish, usually by grandparents who are showing their affection to a dear little child. Taken literally however, it is quite funny and a little absurd.

Thanks, I just wanted to create some funny and memorable nickname and with some joke that can only be understood by Russian speakers and which will (probably) laugh at those people who live in the West, because it is not clear what is written in my nickname.
(DeepL translate)

**Comment by Asek3** [comment] 2023-09-03 09:21
Fixed on latest versions

**Closed as completed by Asek3** 2023-09-03 09:21 UTC
